---
title: "The R Markdown a11y theme"
author: "Alison Hill"
date: "11/11/2020"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(scipen=999)
```

```{r, include=FALSE}
source("functions.R", local = knitr::knit_global())
```


## Exploration 

```{r}
a11y <- read_theme("https://github.com/rstudio/distill/raw/master/inst/rmarkdown/templates/distill_article/resources/a11y.theme")

a11y_v2 <- read_theme("a11y_v2.theme")

a11y_v3 <- read_theme("a11y_v3.theme")

a11y_v4 <- read_theme("a11y_v4.theme")

a11y_v5 <- read_theme("a11y_v5.theme")
```


```{r}
eval_theme <- function(theme) {
  bg <- "#f8f8f8"
  col <- theme %>%
    group_by(fg) %>%
    summarise(abbr = paste(abbr, collapse = "/"),
              .groups = "drop") %>%
    filter(!is.na(fg)) %>% 
    mutate(contrast = contrast_ratio(fg, bg))
  return(list(data = col %>% arrange(contrast), 
              plot1 = col %>% plot_uv(),
              plot2 = plot(prismatic::color(col$fg), 
                   labels = TRUE))
         )
}
```

```{r}
eval_theme(a11y_v2)
eval_theme(a11y_v3)
eval_theme(a11y_v4)
eval_theme(a11y_v5)
```


